### ISSUE TITLE
Errors for PDB IDs: 2PTN, 1OVA

### ISSUE THREAD

**Issue by sidexene** [Electrostatics/osmolytes#4]
PBD IDs 2PTN and 1OVA gave errors like this:
```
dtype: float64
(osmolytes) PS C:\Users\bake213\OneDrive - PNNL\Desktop> mvalue .\Ovabumin_1OVA.pqr
INFO:main:Reading PQR input from .\Ovabumin_1OVA.pqr...
Traceback (most recent call last):
  File "c:\users\bake213\anaconda3\envs\osmolytes\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\bake213\anaconda3\envs\osmolytes\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\bake213\Anaconda3\envs\osmolytes\Scripts\mvalue.exe\__main__.py", line 7, in <module>
  File "c:\users\bake213\anaconda3\envs\osmolytes\lib\site-packages\osmolytes\main.py", line 84, in main
    atoms = parse_pqr_file(pqr_file)
  File "c:\users\bake213\anaconda3\envs\osmolytes\lib\site-packages\osmolytes\pqr.py", line 297, in parse_pqr_file
    atoms.append(Atom(line))
  File "c:\users\bake213\anaconda3\envs\osmolytes\lib\site-packages\osmolytes\pqr.py", line 112, in __init__
    self.parse_pqr(pqr_string)
  File "c:\users\bake213\anaconda3\envs\osmolytes\lib\site-packages\osmolytes\pqr.py", line 143, in parse_pqr
    self.res_num = int(words[4 + chain_offset])
ValueError: invalid literal for int() with base 10: '83A'
(osmolytes) PS C:\Users\bake213\OneDrive - PNNL\Desktop> mvalue .\Glucose_isomerase_1MNZ.pqr
INFO:main:Reading PQR input from .\Glucose_isomerase_1MNZ.pqr...
```

**Comment by sobolevnrm** [comment]
This appears to be due to the `mvalue` code assuming all residue IDs are integers--and incorrectly ignoring insertion codes.
